import './globals.css'
import type { Metadata } from 'next'
import {NavBar, Footer} from '@/components/index'
import React from 'react'
export const metadata: Metadata = {
  title: 'CX Development',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='relative bg-black'>
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
